### ISSUE TITLE
Example in README doesn't work with petgraph 0.8

### ISSUE THREAD

**Issue by zhassan-aws** [a-maier/graph-cycles#2]
With the latest version of petgraph (0.8), the example mentioned in README fails to compile.

```bash
$ cargo new foo && cd foo
    Creating binary (application) `foo` package
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
$ cargo add petgraph graph-cycles
    Updating crates.io index
      Adding petgraph v0.8.1 to dependencies
             Features:
             + graphmap
             + matrix_graph
             + stable_graph
             + std
             - all
             - generate
             - quickcheck
             - rayon
             - serde
             - serde-1
             - serde_derive
             - unstable
      Adding graph-cycles v0.2.0 to dependencies
    Updating crates.io index
     Locking 27 packages to latest Rust 1.89.0-nightly compatible versions
$ vi src/main.rs 
$ cat src/main.rs 
use graph_cycles::Cycles;
use petgraph::graph::Graph;

fn main() {
    let g = Graph::<(), ()>::from_edges([(0, 1), (1, 2), (2, 0)]);

    // find all cycles
    let cycles = g.cycles();
    assert_eq!(cycles.len(), 1);
    assert_eq!(cycles[0].len(), 3);

    // print each cycle in turn
    g.visit_all_cycles(|_g, c| {
        println!("Found new cycle with vertices {c:?}");
    });
}
$ cargo build
   Compiling equivalent v1.0.2
   Compiling allocator-api2 v0.2.21
   Compiling foldhash v0.1.5
   Compiling libc v0.2.172
   Compiling getrandom v0.3.3
   Compiling version_check v0.9.5
   Compiling zerocopy v0.8.25
   Compiling fixedbitset v0.5.7
   Compiling cfg-if v1.0.0
   Compiling once_cell v1.21.3
   Compiling ahash v0.8.12
   Compiling hashbrown v0.15.3
   Compiling indexmap v2.9.0
   Compiling petgraph v0.7.1
   Compiling petgraph v0.8.1
   Compiling graph-cycles v0.2.0
   Compiling foo v0.1.0 (/home/ubuntu/examples/gc/foo)
error[E0599]: no method named `cycles` found for struct `Graph` in the current scope
 --> src/main.rs:8:20
  |
8 |     let cycles = g.cycles();
  |                    ^^^^^^ method not found in `Graph<(), ()>`

error[E0599]: no method named `visit_all_cycles` found for struct `Graph` in the current scope
  --> src/main.rs:13:7
   |
13 |     g.visit_all_cycles(|_g, c| {
   |     --^^^^^^^^^^^^^^^^ method not found in `Graph<(), ()>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `foo` (bin "foo") due to 2 previous errors
```

**Comment by a-maier** [comment]
Thanks for reporting this. I hadn't allowed petgraph 0.8, yet. It should work with the new version 0.3.
